=== KTheMan/webos-apps-repo/content/schemas/api/PackageManifest.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://repo.webosbrew.org/schemas/api/PackageManifest.schema",
  "title": "PackageManifest",
  "description": "Package manifest for webOS homebrew package",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Application ID, e.g., \"com.newco.app.myApp\". Every application has a unique ID created using the reverse-DNS naming convention."
    },
    "version": {
      "type": "string",
      "description": "The application version number in dot-decimal format with three components, e.g., 3.0.2500."
    },
    "type": {
      "type": "string",
      "enum": [
        "web",
        "stub",
        "native",
        "native_builtin",
        "native_appshell",
        "qml"
      ],
      "description": "Identifies the application type. These are the same types used in appinfo.json on webOS."
    },
    "title": {
      "type": "string",
      "description": "The title of the application."
    },
    "appDescription": {
      "type": "string",
      "description": "The description of the application shown in the application details page."
    },
    "iconUri": {
      "type": "string",
      "description": "Image displayed for the app. This is a URL to an image, or data: encoded URI."
    },
    "sourceUrl": {
      "type": "string",
      "description": "Link to source code repository or project homepage, etc."
    },
    "rootRequired": {
      "type": [
        "boolean",
        "string"
      ],
      "enum": [
        true,
        false,
        "optional"
      ],
      "description": "Whether this app requires a rooted/jailbroken TV to work or can optionally use root."
    },
    "ipkUrl": {
      "type": "string",
      "description": "URL to package file."
    },
    "ipkHash": {
      "type": "object",
      "properties": {
        "sha256": {
          "type": "string",
          "description": "Hex encoded SHA-256 hash."
        }
      },
      "minProperties": 1,
      "additionalProperties": false,
      "description": "Hash of package file."
    },
    "ipkSize": {
      "type": "integer",
      "exclusiveMinimum": 0,
      "description": "Size of package file in bytes."
    },
    "installedSize": {
      "type": "integer",
      "exclusiveMinimum": 0,
      "description": "Size of installed package in bytes."
    }
  },
  "required": [
    "id",
    "version",
    "type",
    "title",
    "iconUri",
    "ipkUrl",
    "ipkHash"
  ]
}

=== KTheMan/webos-apps-repo/manifests/youtube.leanback.v4.json
{
  "id": "youtube.leanback.v4",
  "version": "1.1.1",
  "type": "native",
  "title": "YouTube Cobalt AdFree",
  "iconUri": "https://raw.githubusercontent.com/RF1705/youtube-webos-cobalt-adfree/main/assets/largeIcon.png",
  "sourceUrl": "https://github.com/RF1705/youtube-webos-cobalt-adfree",
  "rootRequired": false,
  "ipkUrl": "https://github.com/RF1705/youtube-webos-cobalt-adfree/releases/download/v1.1.1/youtube.leanback.v4_1.1.1_arm.ipk",
  "ipkHash": {
    "sha256": "84235ccda3aa961ec101b2a139c6810ca61fc9e7b5642ad07c97bd4fd6f93768"
  },
  "ipkSize": 20262680
}

=== KTheMan/webos-apps-repo/manifests/com.cathwyler.magicremoteservice.json
{
  "id": "com.cathwyler.magicremoteservice",
  "title": "MagicRemoteService",
  "version": "1.3.10",
  "type": "web",
  "appDescription": "Use your LG Magic Remote as a Windows mouse and control your PC from your LG webOS TV",
  "iconUri": "https://raw.githubusercontent.com/KTheMan/MagicRemoteService-HBC/v1.3.10/MagicRemoteService/Resources/TV/MagicRemoteService/largeIcon.png",
  "sourceUrl": "https://github.com/Cathwyler/MagicRemoteService",
  "rootRequired": false,
  "ipkUrl": "https://github.com/KTheMan/MagicRemoteService-HBC/releases/download/v1.3.10/com.cathwyler.magicremoteservice_all.ipk",
  "ipkHash": {
    "sha256": "53d5526e557b02e4d9ed210b31c96aa095a319560916278e57cf37beeac79311"
  },
  "ipkSize": 114986
}

=== KTheMan/webos-apps-repo/manifests/com.bigbookshelf.tv.json
{
  "id": "com.bigbookshelf.tv",
  "title": "Bigbookshelf",
  "version": "v0.14.3",
  "type": "web",
  "appDescription": "Audiobookshelf client for Smart TVs",
  "iconUri": "https://raw.githubusercontent.com/KTheMan/bigbookshelf/v0.14.3/assets/largeIcon.png",
  "sourceUrl": "https://github.com/KTheMan/bigbookshelf",
  "rootRequired": false,
  "ipkUrl": "https://github.com/KTheMan/bigbookshelf/releases/download/v0.14.3/bigbookshelf-webos.ipk",
  "ipkHash": {
    "sha256": "b4f7e79e49a3701bdc02d8141d8a89804561ef1d4ce0277b7ba0568c3c0a3d09"
  },
  "ipkSize": 3411742
}
